spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first-database
    username: root
    password: 123456
    tomcat:
      max-http-header-size: 10240000
      max-http-post-size: 10240000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0  #Redis数据库索引（默认为0）
    timeout: 5000
    jedis:
      pool:
        max-active: 50  #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20  #连接池中的最大空闲连接
        min-idle: 2  #连接池中的最小空闲连接


server:
  #端口号
  port: 8888


mybatis:
  # 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中了。
  # config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  # mapUnderscoreToCamelCase 是开启驼峰命名。在官方文档的 setting 中可以看到。（目的：数据库的下划线可以对应类中的驼峰）
  configuration:
    map-underscore-to-camel-case: true
